#ifndef REBELLIOUSDATABASE_GLOBAL_H
#define REBELLIOUSDATABASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REBELLIOUSDATABASE_LIBRARY)
#  define REBELLIOUSDATABASE_EXPORT Q_DECL_EXPORT
#else
#  define REBELLIOUSDATABASE_EXPORT Q_DECL_IMPORT
#endif

#endif // REBELLIOUSDATABASE_GLOBAL_H
